### ISSUE TITLE
Return button

### ISSUE THREAD

**Issue by zjohnzheng** [hkamran80/schedules#16]
When you select a schedule, e.g. Acalanes High School or Average Work Day, **there is no return button**. To return to the picker, you need to manually go to the website "http://schedulesapp.herokuapp.com".

Also, I think it would be nice to **animate the transition** from the **picker** to the **countdown page**.
Example: https://flatuicolors.com/      
(When selecting a palette, there is a white slideover. You could do something like that... but maybe instead of white, use blue instead, or a color based on the countdown _[Acalanes is blue, campo is red, work is green..]_)

**Comment by hkamran80** [comment]
Please create a new feature request for the transition animation

**Comment by hkamran80** [comment]
How does clicking on the schedule name sound?

**Comment by hkamran80** [comment]
All development for this issue (part one - return button) will take place in the [`return-button`](https://github.com/hkamran80/schedules/tree/return-button) branch

**Comment by hkamran80** [comment]
See PR #19

**Comment by zjohnzheng** [comment]
Looks good!
