### ISSUE TITLE
Put the Remaining Time in the Tab

### ISSUE THREAD

**Issue by jq-gs** [hkamran80/schedules#179]
The remaining time in the period should be put in the tab, so that you can avoid switching over to that tab every time you want to see how much time is left in a period.

**Comment by hkamran80** [comment]
Should it include seconds?

`01:12:33` or `01:12`?

**Comment by jq-gs** [comment]
It should include seconds, yes. `01:12:33`

**Comment by hkamran80** [comment]
Perfect, thank you!
