### ISSUE TITLE
Merge V3 into production?

### ISSUE THREAD

**Issue by hkamran80** [hkamran80/schedules#40]
Should [version 3](../tree/hh-mm-ss-countdown) (deployed on the [beta site](https://schedulesapp-beta.herokuapp.com) as of January 13, 2020) be pushed on production?

**Comment by zjohnzheng** [comment]
Yes. Version 3 looks great 👍!

**Comment by hkamran80** [comment]
Merging

**Comment by hkamran80** [comment]
After the new logo is uploaded!
